<?php

namespace AppBundle\Repository;

/**
 * Boissonr2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Boissonr2Repository extends \Doctrine\ORM\EntityRepository
{
}
