<?php

namespace AppBundle\Repository;

/**
 * PaltRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaltRepository extends \Doctrine\ORM\EntityRepository
{
}
