<?php

namespace AppBundle\Repository;

/**
 * pizza2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pizza2Repository extends \Doctrine\ORM\EntityRepository
{
}
