<?php

namespace AppBundle\Repository;

/**
 * Plat4Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Plat4Repository extends \Doctrine\ORM\EntityRepository
{
}
