<?php

namespace AppBundle\Repository;

/**
 * PlatdujourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatdujourRepository extends \Doctrine\ORM\EntityRepository
{
}
