<?php

namespace AppBundle\Repository;

/**
 * Platdujour4Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Platdujour4Repository extends \Doctrine\ORM\EntityRepository
{
}
