<?php

namespace AppBundle\Repository;

/**
 * Vins2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Vins2Repository extends \Doctrine\ORM\EntityRepository
{
}
