<?php

namespace AppBundle\Repository;

/**
 * Vins4Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Vins4Repository extends \Doctrine\ORM\EntityRepository
{
}
